
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
//----------------------------------------------------

package edu.mit.csail.sdg.alloy4compiler.parser;

/** Autogenerated by CUP. */
final class CompSym {
  /* terminals */
  public static final int AT = 25;
  public static final int AS = 23;
  public static final int ANY_ARROW_SOME = 3;
  public static final int GT = 45;
  public static final int ARROW = 2;
  public static final int NOTLTE = 72;
  public static final int ONE_ARROW_ANY = 10;
  public static final int ONE2 = 73;
  public static final int ENUM = 36;
  public static final int IDEN = 48;
  public static final int SIG = 92;
  public static final int EXH = 39;
  public static final int COMMA = 31;
  public static final int SUM = 99;
  public static final int RBRACE = 83;
  public static final int RPAREN = 85;
  public static final int LONE_ARROW_LONE = 17;
  public static final int RUN = 86;
  public static final int NOTGTE = 69;
  public static final int ALL = 19;
  public static final int LT = 59;
  public static final int LBRACE = 53;
  public static final int SOME_ARROW_ANY = 6;
  public static final int LPAREN = 58;
  public static final int SHR = 90;
  public static final int NOT = 66;
  public static final int TILDE = 101;
  public static final int PART = 77;
  public static final int SHL = 89;
  public static final int NOTEQUALS = 67;
  public static final int SHA = 91;
  public static final int LONE_ARROW_ONE = 16;
  public static final int SOME_ARROW_LONE = 9;
  public static final int NUMBER = 104;
  public static final int ABSTRACT = 18;
  public static final int SLASH = 94;
  public static final int ONE_ARROW_LONE = 13;
  public static final int NO2 = 63;
  public static final int NOTIN = 70;
  public static final int UNIV = 102;
  public static final int PLUS = 78;
  public static final int FACT = 42;
  public static final int LONE = 57;
  public static final int ONE = 74;
  public static final int EXTENDS = 41;
  public static final int MODULE = 62;
  public static final int DOMAIN = 33;
  public static final int EXACTLY = 38;
  public static final int NONE = 65;
  public static final int SOME2 = 95;
  public static final int FOR = 43;
  public static final int STAR = 97;
  public static final int LONE_ARROW_SOME = 15;
  public static final int ELSE = 35;
  public static final int FUN = 44;
  public static final int DOT = 34;
  public static final int AMPERSAND = 21;
  public static final int INT = 52;
  public static final int LTE = 60;
  public static final int SIGINT = 93;
  public static final int DISJ = 32;
  public static final int EOF = 0;
  public static final int THIS = 100;
  public static final int ANY_ARROW_LONE = 5;
  public static final int BUT = 27;
  public static final int LONE_ARROW_ANY = 14;
  public static final int ALL2 = 20;
  public static final int MINUS = 61;
  public static final int SOME_ARROW_SOME = 7;
  public static final int SUM2 = 98;
  public static final int IN = 51;
  public static final int OR = 76;
  public static final int SET = 88;
  public static final int error = 1;
  public static final int NOTGT = 68;
  public static final int SEQ = 87;
  public static final int GTE = 46;
  public static final int ID = 103;
  public static final int ONE_ARROW_SOME = 11;
  public static final int ONE_ARROW_ONE = 12;
  public static final int COLON = 30;
  public static final int CHECK = 29;
  public static final int ASSERT = 24;
  public static final int SOME = 96;
  public static final int LONE2 = 56;
  public static final int RBRACKET = 84;
  public static final int CARET = 28;
  public static final int EXPECT = 40;
  public static final int PLUSPLUS = 79;
  public static final int RANGE = 82;
  public static final int NO = 64;
  public static final int SOME_ARROW_ONE = 8;
  public static final int AND = 22;
  public static final int ANY_ARROW_ONE = 4;
  public static final int PRIVATE = 81;
  public static final int OPEN = 75;
  public static final int BAR = 26;
  public static final int NOTLT = 71;
  public static final int IMPLIES = 50;
  public static final int LBRACKET = 54;
  public static final int PRED = 80;
  public static final int LET = 55;
  public static final int IFF = 49;
  public static final int EQUALS = 37;
  public static final int HASH = 47;
}

