
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
//----------------------------------------------------

package edu.mit.csail.sdg.alloy4compiler.parser;

/** Autogenerated by CUP. */
final class CompSym {
  /* terminals */
  public static final int AT = 25;
  public static final int AS = 23;
  public static final int ANY_ARROW_SOME = 3;
  public static final int GT = 44;
  public static final int ARROW = 2;
  public static final int NOTLTE = 71;
  public static final int ONE_ARROW_ANY = 10;
  public static final int ONE2 = 72;
  public static final int IDEN = 47;
  public static final int SIG = 91;
  public static final int EXH = 38;
  public static final int COMMA = 31;
  public static final int SUM = 98;
  public static final int RBRACE = 82;
  public static final int RPAREN = 84;
  public static final int LONE_ARROW_LONE = 17;
  public static final int RUN = 85;
  public static final int NOTGTE = 68;
  public static final int ALL = 19;
  public static final int LT = 58;
  public static final int LBRACE = 52;
  public static final int SOME_ARROW_ANY = 6;
  public static final int LPAREN = 57;
  public static final int SHR = 89;
  public static final int NOT = 65;
  public static final int TILDE = 100;
  public static final int PART = 76;
  public static final int SHL = 88;
  public static final int NOTEQUALS = 66;
  public static final int SHA = 90;
  public static final int LONE_ARROW_ONE = 16;
  public static final int SOME_ARROW_LONE = 9;
  public static final int NUMBER = 103;
  public static final int ABSTRACT = 18;
  public static final int SLASH = 93;
  public static final int ONE_ARROW_LONE = 13;
  public static final int NO2 = 62;
  public static final int NOTIN = 69;
  public static final int UNIV = 101;
  public static final int PLUS = 77;
  public static final int FACT = 41;
  public static final int LONE = 56;
  public static final int ONE = 73;
  public static final int EXTENDS = 40;
  public static final int MODULE = 61;
  public static final int DOMAIN = 33;
  public static final int EXACTLY = 37;
  public static final int NONE = 64;
  public static final int SOME2 = 94;
  public static final int FOR = 42;
  public static final int STAR = 96;
  public static final int LONE_ARROW_SOME = 15;
  public static final int ELSE = 35;
  public static final int FUN = 43;
  public static final int DOT = 34;
  public static final int AMPERSAND = 21;
  public static final int INT = 51;
  public static final int LTE = 59;
  public static final int SIGINT = 92;
  public static final int DISJ = 32;
  public static final int EOF = 0;
  public static final int THIS = 99;
  public static final int ANY_ARROW_LONE = 5;
  public static final int BUT = 27;
  public static final int LONE_ARROW_ANY = 14;
  public static final int ALL2 = 20;
  public static final int MINUS = 60;
  public static final int SOME_ARROW_SOME = 7;
  public static final int SUM2 = 97;
  public static final int IN = 50;
  public static final int OR = 75;
  public static final int SET = 87;
  public static final int error = 1;
  public static final int NOTGT = 67;
  public static final int SEQ = 86;
  public static final int GTE = 45;
  public static final int ID = 102;
  public static final int ONE_ARROW_SOME = 11;
  public static final int ONE_ARROW_ONE = 12;
  public static final int COLON = 30;
  public static final int CHECK = 29;
  public static final int ASSERT = 24;
  public static final int SOME = 95;
  public static final int LONE2 = 55;
  public static final int RBRACKET = 83;
  public static final int CARET = 28;
  public static final int EXPECT = 39;
  public static final int PLUSPLUS = 78;
  public static final int RANGE = 81;
  public static final int NO = 63;
  public static final int SOME_ARROW_ONE = 8;
  public static final int AND = 22;
  public static final int ANY_ARROW_ONE = 4;
  public static final int PRIVATE = 80;
  public static final int OPEN = 74;
  public static final int BAR = 26;
  public static final int NOTLT = 70;
  public static final int IMPLIES = 49;
  public static final int LBRACKET = 53;
  public static final int PRED = 79;
  public static final int LET = 54;
  public static final int IFF = 48;
  public static final int EQUALS = 36;
  public static final int HASH = 46;
}

